### ISSUE TITLE
File header mismatch

### ISSUE THREAD

**Issue by cyberfox213** [ladosha/lis2-save-editor#5]
I have opened my LIS2 save that works, but the editor says no, possible workaround?
![immagine](https://user-images.githubusercontent.com/6090195/128867015-c3cd51cc-88a5-4d84-bdd0-3a6fd5363ace.png)

**Comment by ladosha** [comment]
Hello, unfortunately these days I don't have time to maintain the project. The save file is likely generated by a version later than Episode 3's release.

**Comment by cyberfox213** [comment]
i just completed the episode 1

**Comment by TesenDesk** [comment]
Hello!
This program works with save files that were created by the version of the game released BEFORE May 9, 2019 (when the third episode was released). After this date, the saving algorithm has changed. If you have a later version or steam version, this program will not work with your saves.
P.S. @ladosha I would like to take this opportunity to thank you for this program. It helped me a lot. hopefully in the future you will have time to update it to work with all episodes.
P.P.S. Sorry for my bad English

**Comment by IgelRM** [comment]
Hi all, commenting in this thread since there seems to be a bit of interest.
1. The disclaimer in the readme could say "Broken since May 2019" at the top for a TLDR. Perhaps also archive this repo, so it's clear this isn't actively maintained anymore.
2. The save is zlib compressed and can be uncompressed as described [in this issue](https://github.com/ladosha/lis2-save-editor/issues/3). One can compile the master branch which can mostly open uncompressed complete season saves.
3. No FactNames will be visible as they are were manually added to the tool (mostly number salad).

[@TesenDesk Your English is very comprehensible]

**Comment by ladosha** [comment]
Hello all,

@IgelRM thanks for commenting and for the suggestions. I will archive the repository and have edited the readme a bit.
@TesenDesk I am happy that the project was useful. :) 

And yes I remember manually inspecting the files with a HEX editor and deciphering the fact names.
